# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[33,37)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The mod license
license="MIT"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="zoomerzoom" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.0" #mandatory
 # A display name for the mod
displayName="Zoomer Zoom" #mandatory
# A text field displayed in the mod UI
authors="SirOMGitsYOU" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Zoomer Zoom, This aims to be the best Zoom Mod on the market, as ported from Logical Zoom on Fabric, Zoomer Zoom offers additional features such as mouse scrollwheel zoom to add additional and less zoom.
'''

[[dependencies.zoomerzoom]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="CLIENT"

[[dependencies.zoomerzoom]]
modId="minecraft"
mandatory=true
versionRange="[1.16,)"
ordering="NONE"
side="CLIENT"